import { jsPDF } from "jspdf";
import "jspdf-autotable";

export const generateMonthlyReport = (income, expenses, stats, budget) => {
    const doc = new jsPDF();
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

    // Header
    doc.setFontSize(22);
    doc.setTextColor(33, 150, 243);
    doc.text("Personal Finance Report", 105, 20, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 28, { align: "center" });
    doc.text(`Period: ${monthYear}`, 105, 34, { align: "center" });

    // Summary Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Financial Summary", 14, 50);

    doc.setFontSize(11);
    const summaryData = [
        ["Total Income", `₹${stats.totalIncome.toLocaleString()}`],
        ["Total Expenses", `₹${stats.totalExpenses.toLocaleString()}`],
        ["Net Savings", `₹${stats.netBalance.toLocaleString()}`],
        ["Savings Rate", `${stats.savingsRate}%`],
    ];

    if (budget.monthlyBudget > 0) {
        const currentMonthExpenses = expenses.filter(exp => {
            const expDate = new Date(exp.date);
            return expDate.getMonth() === now.getMonth() && expDate.getFullYear() === now.getFullYear();
        });
        const spent = currentMonthExpenses.reduce((acc, exp) => acc + Number(exp.amount), 0);
        summaryData.push(
            ["Monthly Budget", `₹${budget.monthlyBudget.toLocaleString()}`],
            ["Budget Used", `${((spent / budget.monthlyBudget) * 100).toFixed(1)}%`]
        );
    }

    doc.autoTable({
        startY: 55,
        head: [["Metric", "Value"]],
        body: summaryData,
        theme: "grid",
        headStyles: { fillColor: [33, 150, 243], textColor: 255 },
        alternateRowStyles: { fillColor: [240, 248, 255] },
        styles: { fontSize: 11 }
    });

    // Income Details
    if (income.length > 0) {
        doc.setFontSize(16);
        doc.text("Income Details", 14, doc.lastAutoTable.finalY + 15);

        doc.autoTable({
            startY: doc.lastAutoTable.finalY + 20,
            head: [["Title", "Category", "Date", "Amount"]],
            body: income.map(item => [
                item.title,
                item.category,
                new Date(item.date).toLocaleDateString(),
                `₹${Number(item.amount).toLocaleString()}`
            ]),
            theme: "grid",
            headStyles: { fillColor: [76, 175, 80], textColor: 255 },
            alternateRowStyles: { fillColor: [232, 245, 233] },
            styles: { fontSize: 10 }
        });
    }

    // Expense Details
    if (expenses.length > 0) {
        doc.setFontSize(16);
        doc.text("Expense Details", 14, doc.lastAutoTable.finalY + 15);

        doc.autoTable({
            startY: doc.lastAutoTable.finalY + 20,
            head: [["Title", "Category", "Date", "Amount"]],
            body: expenses.map(item => [
                item.title,
                item.category,
                new Date(item.date).toLocaleDateString(),
                `₹${Number(item.amount).toLocaleString()}`
            ]),
            theme: "grid",
            headStyles: { fillColor: [244, 67, 54], textColor: 255 },
            alternateRowStyles: { fillColor: [255, 235, 238] },
            styles: { fontSize: 10 }
        });
    }

    // Category Breakdown
    doc.setFontSize(16);
    doc.text("Category Breakdown", 14, doc.lastAutoTable.finalY + 15);

    const incomeByCategory = {};
    const expensesByCategory = {};

    income.forEach(item => {
        incomeByCategory[item.category] = (incomeByCategory[item.category] || 0) + Number(item.amount);
    });

    expenses.forEach(item => {
        expensesByCategory[item.category] = (expensesByCategory[item.category] || 0) + Number(item.amount);
    });

    const categoryData = [
        ...Object.entries(incomeByCategory).map(([cat, amount]) => ["Income", cat, `₹${amount.toLocaleString()}`]),
        ...Object.entries(expensesByCategory).map(([cat, amount]) => ["Expense", cat, `₹${amount.toLocaleString()}`])
    ];

    doc.autoTable({
        startY: doc.lastAutoTable.finalY + 20,
        head: [["Type", "Category", "Total"]],
        body: categoryData,
        theme: "grid",
        headStyles: { fillColor: [156, 39, 176], textColor: 255 },
        styles: { fontSize: 10 }
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Personal Finance Tracker", 105, 285, { align: "center" });

    // Save
    doc.save(`Finance_Report_${now.toISOString().split('T')[0]}.pdf`);
};
